name: Release
on:
  push:
    tags-ignore:
      - latest

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn clean package
      - uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: target/Oregen3*.jar
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            target/Oregen3*.jar