name: Release
on:
  push:
    tags-ignore:
      - latest

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/Oregen3*.jar
      - name: Release build artifacts
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          files: build/libs/Oregen3*.jar